version: "3"
  
services:
  db:
    restart: always
    image: mongo
    ports:
      - "27017:27017"

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "5005:5005"

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    ports:
      - "5007:5007"
